### ISSUE TITLE
Cannot find generator when trying to initialize app

### ISSUE THREAD

**Issue by jdivock** [flightjs/generator-flight#3] opened 2013-05-22 21:09 UTC
Running

```
yo flight 
```

or 
    yo flight:app

gives

```
Error flight

You don't seem to have a generator with the name flight installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 8 registered generators run yo with the `--help` option.
```

But when I go to check out the generators I have installed I can see all the flight targets

```
Please choose a generator below.


Flight
  flight:lib:generators:all
  flight:lib:generators:app
  flight:lib:generators:component
  flight:lib:generators:mixin
  flight:lib:generators:page

Mocha
   mocha:app
   mocha:generator

Webapp
   webapp:app
```

My other generators work fine.

**Comment by jdivock** [comment] 2013-05-22 21:12
Update, derp. I have to run flight:lib:generators:app to get the scaffolding, which works but doesn't seem right.

**Comment by necolas** [comment] 2013-05-22 21:32
I can't reproduce this. Please can you make sure you have the latest version of `yo` installed (which shouldn't include the mocha and webapp generators).

**Comment by jdivock** [comment] 2013-05-23 13:49
I'm running yo -v 1.0.0-beta.5

I'm running this through git bash on a win7 machine, so that may have something to do with it.

**Comment by necolas** [comment] 2013-05-23 23:35
I could reproduce on Windows. This looks like a Yeoman bug but hopefully there's an interim solution they can point me to. I created an issue here - https://github.com/yeoman/generator/issues/254

**Comment by necolas** [comment] 2013-05-25 15:23
This has now been fixed in yeoman-generator, just waiting for a new release to come out before I close this. Then you should just be able to reinstall and get the fixed version.

**Comment by necolas** [comment] 2013-05-30 16:43
Hey, I'm going to close this because it's not a bug with this repo. I've been pestering the Yeoman team to make a new patch release with the fix for this; if you'd like to help hurry them along, let them know here:  https://github.com/yeoman/generator/issues/254

Thanks again for reporting this and helping it get patched upstream.

**Closed as completed by necolas** 2013-05-30 16:43 UTC

**Comment by necolas** [comment] 2013-06-06 04:54
This should be fixed now @jdivock
